export enum BillingCodeStandard {
  CPT = 'CPT',
  NDC = 'NDC',
  HCPCS = 'HCPCS',
  RC = 'RC',
  ICD = 'ICD',
  MS_DRG = 'MS-DRG',
  R_DRG = 'R-DRG',
  S_DRG = 'S-DRG',
  APS_DRG = 'APS-DRG',
  AP_DRG = 'AP-DRG',
  APR_DRG = 'APR_DRG',
  APC = 'APC',
  LOCAL = 'LOCAL',
  EAPC = 'EAPC',
  HIPPS = 'HIPPS',
  CDT = 'CDT',
}

export enum BillingClass {
  Professional = 'professional',
  Institutional = 'institutional',
}

export enum PlaceOfService {
  Pharmacy = '01',
  TelehealthProvidedOtherThanInPatientsHome = '02',
  School = '03',
  HomelessShelter = '04',
  IndianHealthServiceFreeStandingFacility = '05',
  IndianHealthServiceProviderBasedFacility = '06',
  Tribal638FreeStandingFacility = '07',
  Tribal638ProviderBasedFacility = '08',
  PrisonCorrectionalFacility = '09',
  TelehealthProvidedInPatientsHome = '10',
  Office = '11',
  Home = '12',
  AssistedLivingFacility = '13',
  GroupHome = '14',
  MobileUnit = '15',
  TemporaryLodging = '16',
  WalkInRetailHealthClinic = '17',
  PlaceOfEmploymentWorksite = '18',
  OffCampusOutpatientHospital = '19',
  UrgentCareFacility = '20',
  InpatientHospital = '21',
  OnCampusOutpatientHospital = '22',
  EmergencyRoomHospital = '23',
  AmbulatorySurgicalCenter = '24',
  BirthingCenter = '25',
  MilitaryTreatmentFacility = '26',
  OutreachSiteStreet = '27',
  SkilledNursingFacility = '31',
  NursingFacility = '32',
  CustodialCareFacility = '33',
  Hospice = '34',
  AmbulanceLand = '41',
  AmbulanceAirOrWater = '42',
  IndependentClinic = '49',
  FederallyQualifiedHealthCenter = '50',
  InpatientPsychiatricFacility = '51',
  PsychiatricFacilityPartialHospitalization = '52',
  CommunityMentalHealthCenter = '53',
  IntermediateCareFacilityIndividualsWithIntellectualDisabilities = '54',
  ResidentialSubstanceAbuseTreatmentFacility = '55',
  PsychiatricResidentialTreatmentCenter = '56',
  NonResidentialSubstanceAbuseTreatmentFacility = '57',
  NonResidentialOpioidTreatmentFacility = '58',
  MassImmunizationCenter = '60',
  ComprehensiveInpatientRehabilitationFacility = '61',
  ComprehensiveOutpatientRehabilitationFacility = '62',
  EndStageRenalDiseaseTreatmentFacility = '65',
  ProgramsOfAllInclusiveCareForTheElderlyPACECenter = '66',
  PublicHealthClinic = '71',
  RuralHealthClinic = '72',
  IndependentLaboratory = '81',
  OtherPlaceOfService = '99',
}
